const activities = [
    "Watch a movie",
    "Read a book",
    "Listen to a podcast",
    "Paint a picture",
    "Go for a run",
    "Try a new recipe",
    "Play a board game",
    "Write a short story",
    "Do a yoga session",
    "Learn a new language",
    "Solve a puzzle",
    "Take a nature walk",
    "Knit or crochet something",
    "Play an instrument",
    "Stargaze at night",
    "Try photography",
    "Build a DIY craft",
    "Explore a museum",
    "Dance to your favorite songs",
    "Meditate for relaxation",
    "Go cycling around your neighborhood",
    "Call or text a friend",
    "Organize your workspace",
    "Create a playlist",
    "Journal your thoughts",
    "Visit a farmers’ market",
    "Try gardening",
    "Bake a cake or cookies",
    "Play video games",
    "Learn basic coding",
    "Research a historical event",
    "Take an online course",
    "Write a poem",
    "Try calligraphy",
    "Visit a local café",
    "Make a scrapbook",
    "Try woodworking",
    "Take a nap",
    "Join a sports club",
    "Do a digital detox",
    "Build a Lego creation",
    "Sketch a comic strip",
    "Go birdwatching",
    "Try indoor rock climbing",
    "Watch a documentary",
    "Make handmade gifts",
    "Set up a picnic",
    "Try roller skating",
    "Create an origami figure",
    "Participate in a trivia game",
    "Test out new makeup looks",
    "Start a YouTube channel",
    "Learn about astronomy",
    "Write a handwritten letter",
    "Try a virtual escape room",
    "Experiment with science experiments",
    "Play chess or checkers",
    "Create a vision board",
    "Take silly photos with friends",
    "Explore a new hiking trail",
    "Try a new workout routine",
    "Play frisbee at the park",
    "Start a travel bucket list",
    "Design your own clothing",
    "Cook an international dish",
    "Rewatch childhood cartoons",
    "Make a time capsule",
    "Build a paper airplane race",
    "Learn how to juggle",
    "Write a song or lyrics",
    "Explore urban street art",
    "Try indoor gardening",
    "Do charity work or volunteering",
    "Go to a food festival",
    "Host a game night",
    "Learn to do magic tricks",
    "Build a blanket fort",
    "Try making pottery",
    "Research family genealogy",
    "Ride a horse",
    "Go thrift shopping",
    "Make homemade candles",
    "Solve a crossword puzzle",
    "Start a blog",
    "Try painting with watercolors",
    "Create a stop-motion animation",
    "Write down your dreams",
    "Try a martial arts class",
    "Build a playlist based on a mood",
    "Take an afternoon tea break",
    "Practice deep breathing exercises",
    "Play in a virtual reality game",
    "Learn sign language",
    "Try wild swimming (if safe)",
    "Go camping in your backyard",
    "Make a DIY face mask",
    "Join a local book club",
    "Learn how to sew",
    "Watch live theater or an improv show",
    "Try archery"
]

export default activities;